// Auto-generated by extract.js with raw CSS bundling
import React from 'react';
import { exercises as rawExercises, quizzes as rawQuizzes } from './exercises.json';

export const exercisesList = rawExercises;
export const quizzesList = rawQuizzes;

export const exerciseComponents = {
  '007-building-using-a-component': React.lazy(() => import('./exercises/007-building-using-a-component/App.jsx')),
  '012-outputting-dynamic-content': React.lazy(() => import('./exercises/012-outputting-dynamic-content/App.jsx')),
  '016-working-with-props': React.lazy(() => import('./exercises/016-working-with-props/App.jsx')),
  '021-component-composition': React.lazy(() => import('./exercises/021-component-composition/App.jsx')),
  '024-reacting-to-events': React.lazy(() => import('./exercises/024-reacting-to-events/App.jsx')),
  '026-configuring-event-handlers': React.lazy(() => import('./exercises/026-configuring-event-handlers/App.jsx')),
  '030-working-with-state': React.lazy(() => import('./exercises/030-working-with-state/App.jsx')),
  '034-conditional-content': React.lazy(() => import('./exercises/034-conditional-content/App.jsx')),
  '036-dynamic-styling': React.lazy(() => import('./exercises/036-dynamic-styling/App.jsx')),
  '038-dynamic-list-content': React.lazy(() => import('./exercises/038-dynamic-list-content/App.jsx')),
};

// Raw CSS strings loaded directly via Vite
export const exerciseRawStyles = import.meta.glob('./exercises/*/index.css', {
  query: '?raw',
  import: 'default',
  eager: true,
});
